name: haushalt_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.4.0
  provider: ^6.1.5
  intl: ^0.20.2
  firebase_messaging: ^15.2.6
  firebase_core: ^3.13.1
  firebase_analytics: ^11.4.6
  flutter_local_notifications: ^19.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
